### PR TITLE
Updated OpenAi gem 7.0.1

### PR DESCRIPTION
**Pull request by Rmpanga**
## Description

Updated OpenAI Gem to 7.0.1 

# Testing Done

1. Ran both system tests and regular tests
2. Deployed changes locally and confirmed backwards compatibility
3. Confirmed new Gem was deployed in Rails

### CODE REVIEW

**Comment by krschacht** [comment]
@Rmpanga I just realized that I need the newest version of this gem for a feature I'm working on right now (text to speech using OpenAI)! Even though I left you a comment about the README, I'm anxious to get this merged into main so I can pull it into my branch so I've just done a revision of the README instructions. Take a look at that and let me know if you have any further comments on it. We can continue to improve them in a followup PR.

**Comment by krschacht** [comment]
Oh, and while I have your attention :) I'd love to hear what motivated you to check out HostedGPT? And if you have any feedback on things that are important to you (e.g. missing functionality) let me know and I can take that into consideration. Also, if you've had any trouble with it, that's helpful for me to hear as well.

**Comment by Rmpanga** [comment]
Thanks for updating @krschacht. I'm proficient (not an expert) with rails and wanted to see if there were any open source Rails ChatGPT projects. I really liked how the project was structured especially having tests & fixtures. I wanted to experiment with different ideas and this project has been very helpful. 

Happy to help with the  ruby-anthropic gem as well.

**Comment by Rmpanga** [comment]
One question I did have was the model structure. 

I see the attendant was for `Conversations` to mirror OpenAI threads. 
However I noticed that `Assistants` do not mirror OpenAI assistants 

Was the original intent  of `Assistants` to mirror OpenAI assistants?

**Comment by krschacht** [comment]
Great to hear! One of my hopes for this project is that it’s a good starting point for other projects. Let me move this conversation over to here: https://github.com/allyourbot/hostedgpt/discussions/345

**Pull request merged**
